---
title: "ESM 262 Assignment 2"
author: "Sara Orofino"
date: "2/26/2020"
output: html_document
---

#{.tabset}

##Load Packages
```{r packages}
library(tidyverse)
```


##Function
 
Old function just in case:  
```{r}
#only want results for the number of unique locations (not entire length of input data)
  unique_loc <- unique(fish_data$location)
  
  #Set up a results dataframe for the location dependent information
  results <- data.frame(location = rep(NA, length(unique_loc)),
                        common_fish = rep(NA, length(unique_loc)),
                        total_rev = rep(NA, length(unique_loc)))
  
  #Fishery results should be based on the number of unique fisheries
  unique_fish <- unique(fish_data$fish)
  
  #Set up a dataframe for the fishery dependent information
  fish.results = data.frame(fishery = rep(NA, length(unique_fish)),
                            fishery_rev = rep(NA, length(unique_fish)))
  
  #Want to have the fish data as a factor:
  fish_data$fish = as.factor(fish_data$fish)
  
  #Compute all the location depedent results:
  for(i in 1:length(unique_loc)){
    
    results$location[i] <- unique_loc[i] #set the location
    
    #Subset by location to find which fish had the highest catch for each location
    location_name <- results$location[i]
    sub_location <- subset(fish_data, location == location_name)
    sub_max <- names(which.max(summary(sub_location$fish)))
    results$common_fish[i] <- sub_max
    
    #Calculate the revenue for each location - add a price column to the subsetted data, find price for each fish & calc revenue
    for(j in 1:7){
    fish.name <- sub_location$fish[j]
    fish.price <- fish_prices$price[fish_prices$fish == fish.name]
    sub_location$fish_price[j] <- fish.price
    fish.catch <- summary(sub_location$fish)[j]
    sub_location$revenue[j] <- fish.price * fish.catch
    }

    total_rev <- sum(sub_location$revenue)
    results$total_rev[i] <- total_rev
  }
  
  #Compute the fishery dependent results
  for(f in 1:length(unique_fish)){
    fish.results$fishery <- unique_fish[f] #set the fishery
    fishname <- fish.results$fishery[f]
    sub_fishery <- subset(fish_data, fish == fishname)
    fishprice <- fish_prices$price[fish_prices$fish == fishname]
    fishcatch <- summary(sub_fishery$fish)[f]
    sub_fishery$fishrev[f] <- fishprice * fishcatch
    
    fish.results$fishery_rev[f] <- sub_fishery$fishrev[f]
  }
  
```

##Data
Generate the input data for the function  

Inputs:  
 * prices for different fish  
 * number of each fish species caught by location  
 
```{r data, warning=FALSE}
#Create a vector of possible fish
possible_fish <- c("cod", "tuna", "halibut", "salmon", "bass", "grouper", "rockfish")  

#Assign prices for the different fish - let's say prices vary from $3/lb to $30/lb
prices <- runif(length(possible_fish),3,30)

#Create the input table of fish and prices:
fish.prices <- data.frame(fish = possible_fish, price = prices)

#Set up the dataframe for catch at each of the 5 locations:
catch = data.frame(Alaska = rep(NA,length(possible_fish)), California = rep(NA, length(possible_fish)),
                   Mexico = rep(NA, length(possible_fish)),
                   Maine = rep(NA, length(possible_fish)), North_Carolina = rep(NA, length(possible_fish)))

#Let's say catch will vary from 10 fish to 200 fish; draw number of each fish caught at each location:
for(i in 1:length(possible_fish)){
  catch$Alaska[i] <- round(runif(1,10,200),0)
  catch$California[i] <- round(runif(1,10,200),0)
  catch$Mexico[i] <- round(runif(1,10,200),0)
  catch$Maine[i] <- round(runif(1,10,200),0)
  catch$North_Carolina[i] <- round(runif(1,10,200),0)
}

#Add fish types as row names
rownames(catch) <- possible_fish
```

##Run Function
```{r run-function}
source("fish_revenue.R")

fish_results <- fish_revenue(fish_data = catch, fish_prices = fish.prices)
```


##Graph Output

Graph of revenue by location and total revenue (text)  