---
title: "assignment1_2.9"
author: "Sara Orofino"
date: "2/10/2020"
output: html_document
---

#{.tabset}  


##Why this Course

I'm completing the Environmental Data Science focus and this is one of the required classes. I'm interested in learning how to write my own R packages and become more advanced with functions to accomplish repetitive data analysis tasks.   

##Data Science Background

I started learning how to use R/RStudio and git/GitHub last year when I started at Bren. I've taken both of Allison's data courses and both of Frew's GIS classes where we did a bit of command line coding with git as well as publishing GIS maps to GitHub. Last spring I started working on a data analysis research project with Mark Buntaine. In this project I have brought together about 15 data sets, wrangled them into one set of analysis data, and completed a regression analysis all in R. My group project is also heavily based in R. With my teammates, I combined a biological fisheries model with a management model we created to simulate decision making on various time intervals. These models were contained within a larger function and had several sets of if statements and time dependent loops. 